### ISSUE TITLE
Optimise parse phase for any performance gain

### ISSUE THREAD

**Issue by bradleyfalzon** [bradleyfalzon/apicompat#3]
abicheck is two phase, the first phase determines all the exported declarations (once for the before version, and once again for the after version), the second phase compares all the .

The first phase runs in parallel now, but the second phase does not.

**Comment by bradleyfalzon** [comment]
Comparison of the phases, need to focus on parsing phase, but for majority of repos, it's actually OK.

These numbers seem high, but they're checking the entire repo, not just the buildable components, so don't compare to build times.

```
kubernetes: Parse time: 46.362144344s, Diff time: 395.351404ms, Sort time: 108.22µs
go: Parse time: 15.746992691s, Diff time: 177.485421ms, Sort time: 2.7346ms
```

**Comment by hydroflame** [comment]
I profiled the program and it looks like most of the time is wasted on syscalls and the GC.

**Comment by bradleyfalzon** [comment]
Excellent thanks, I hadn't had time to recheck recently, cheers, I'll close then.

**Comment by hydroflame** [comment]
Are you excluding folders in which nothing has changed between the revisions ?

**Comment by bradleyfalzon** [comment]
No it's not, the vcs shows content for all files at both revisions regardless if it's changed or not. This is definitely a good idea for an optimisation, but isn't straight forward, at least, isn't a minor change. If projects do have issues with performance, I think this'll be a good first step.

**Comment by bradleyfalzon** [comment]
Actually, it might not be possible, as the project needs to be built completely for the type checker at each version, so I think the majority of the time will still be in parse phase.

**Comment by hydroflame** [comment]
http://stackoverflow.com/questions/1552340/how-to-list-the-file-names-only-that-changed-between-two-commits

**Comment by bradleyfalzon** [comment]
Yeah, but I still need a complete project in order to type check it. As the type checking takes majority of the time, any other optimisations may not be as significant. 

Eg, in the kubernetes examples (this is from an old revision) `kubernetes: Parse time: 46.362144344s, Diff time: 395.351404ms, Sort time: 108.22µs`

I can't optimise that 46 seconds down any further, becaues go/build type checks an entire package.

**Comment by hydroflame** [comment]
wait the differential takes all the time ? That's odd thats not what I saw, give me a couple of days I'll nail it down

**Comment by bradleyfalzon** [comment]
No no, re-read, the parse time takes all the time, the type checking is the parse stage.

**Comment by hydroflame** [comment]
which operations are performed during the "diff time" ?

**Comment by hydroflame** [comment]
oh
s vs ms

**Comment by bradleyfalzon** [comment]
Yeah the diff time is the actual api checking, which is negligible compared to the parse time (building the projects).
