### ISSUE TITLE
Go Dependency Management Discussion

### ISSUE THREAD

**Issue by itsjamie** [bradleyfalzon/apicompat#33]
Hello! I was reading a blog post at https://blog.gopheracademy.com/advent-2016/saga-go-dependency-management/ about the tool that a group of devs, "Vendor Committee" have been working on for Go to solve the issues, and they explicitly called out for a tool: 

> A tool that can statically analyze a project and suggest the next SemVer tag to use for the next release

I was wondering if you @bradleyfalzon wouldn't mind if I put forward this tool as a starting point perhaps for that?

**Comment by bradleyfalzon** [comment]
No problems at all, I'm working on related work, to promote this further, it certainly is one of the reasons I built this tool.

I just haven't thought through whether this tool should detect the semver tags itself, or whether another tool should wrap this (i.e. another library, or the dependency tool itself).

**Comment by itsjamie** [comment]
Personally, I think another tool could more easily handle that as they likely already have that VCS code, and I don't see why you need to pollute this with the different tools and fetching their tags. Perhaps the tool they are building could utilize apicompat when running an operation against their manifest or lock file. Well, thanks for the quick turn around, I'll link to here in the Slack #vendor channel. Thanks!

**Comment by itsjamie** [comment]
Nevermind, I see you already posted there! Haha. Should have checked there first. Thank you!

**Comment by bradleyfalzon** [comment]
No problems,

But do note, apicompat does need to know about the VCS as it accesses previous versions of the file to determine what's changed.

**Comment by itsjamie** [comment]
Oh I didn't realize that, I had only every used it via the web interface, so I assumed it was left as an exercise to the reader to make it VCS aware.. this will be even easier to implement in a CI setup than I thought.

Thank you!
